; Script generated by Antigravity Senior Engineering Assistant
; Inno Setup Script for PNJ Jewelry Store Management System

#define MyAppName "PNJ Jewelry Store Manager"
#define MyAppVersion "2.0.0"
#define MyAppPublisher "PNJ Enterprise Solutions"
#define MyAppExeName "FINAL_DotNet.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".pnj"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
AppId={{D1941B34-8BA5-480E-8E7E-B3AB51D21FCE}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\PNJ Jewelry Manager
ChangesAssociations=yes
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir=Output
OutputBaseFilename=PNJ_Jewelry_Manager_Setup_v2.0
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "Staging\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "Staging\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\Database\QL_CuaHangDaQuy_PNJ.bak"; DestDir: "{app}\Database"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function InitializeSetup(): Boolean;
var
  NetFrameRelease: Cardinal;
begin
  Result := True;
  if RegQueryDWordValue(HKLM, 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', 'Release', NetFrameRelease) then
  begin
    if NetFrameRelease < 461808 then
    begin
      MsgBox('This application requires Microsoft .NET Framework 4.7.2 or higher.'#13#10'Please install .NET Framework 4.7.2 before proceeding.', mbInformation, MB_OK);
      Result := False;
    end;
  end;
end;
