//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL_DotNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChatLieu()
        {
            this.ChiTietChatLieux = new HashSet<ChiTietChatLieu>();
            this.ChiTietPhieuThuMuas = new HashSet<ChiTietPhieuThuMua>();
        }
    
        public int ChatLieuId { get; set; }
        public string TenChatLieu { get; set; }
        public decimal GiaMuaVao { get; set; }
        public decimal GiaBanRa { get; set; }
        public bool DangHoatDong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietChatLieu> ChiTietChatLieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuThuMua> ChiTietPhieuThuMuas { get; set; }
    }
}
