//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL_DotNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public int ChiTietPhieuNhapId { get; set; }
        public int PhieuNhapId { get; set; }
        public int SanPhamId { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGiaNhap { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
