//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL_DotNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuThuMua
    {
        public int ChiTietPhieuThuMuaId { get; set; }
        public int PhieuThuMuaId { get; set; }
        public int ChatLieuId { get; set; }
        public Nullable<int> SanPhamId { get; set; }
        public string TenSanPhamThu { get; set; }
        public decimal TrongLuong { get; set; }
        public string DonViTinh { get; set; }
        public decimal DonGiaThuMua { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual ChatLieu ChatLieu { get; set; }
        public virtual PhieuThuMua PhieuThuMua { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
