//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class MauEmail
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MauEmail()
    {
        this.NhatKyGuiEmails = new HashSet<NhatKyGuiEmail>();
    }

    public int MauEmailId { get; set; }
    public string TenMau { get; set; }
    public string TieuDeMau { get; set; }
    public string NoiDungMau { get; set; }
    public bool DangHoatDong { get; set; }
    public Nullable<int> TaiKhoanCapNhatId { get; set; }
    public System.DateTime NgayCapNhat { get; set; }

    public virtual TaiKhoan TaiKhoan { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<NhatKyGuiEmail> NhatKyGuiEmails { get; set; }
}
