//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class NhanVien
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NhanVien()
    {
        this.HoaDons = new HashSet<HoaDon>();
        this.PhieuNhaps = new HashSet<PhieuNhap>();
        this.PhieuThuMuas = new HashSet<PhieuThuMua>();
        this.TaiKhoans = new HashSet<TaiKhoan>();
    }

    public int NhanVienId { get; set; }
    public string HoTen { get; set; }
    public string GioiTinh { get; set; }
    public Nullable<System.DateTime> NgaySinh { get; set; }
    public string SoDienThoai { get; set; }
    public string Email { get; set; }
    public string DiaChi { get; set; }
    public string ChucVu { get; set; }
    public bool DangLamViec { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HoaDon> HoaDons { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PhieuNhap> PhieuNhaps { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PhieuThuMua> PhieuThuMuas { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
}
