//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL_DotNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyGuiEmail
    {
        public long NhatKyGuiEmailId { get; set; }
        public int TaiKhoanId { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public Nullable<int> HoaDonId { get; set; }
        public Nullable<int> MauEmailId { get; set; }
        public System.DateTime ThoiGianGui { get; set; }
        public string EmailNhan { get; set; }
        public string TieuDe { get; set; }
        public string LoaiGui { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual MauEmail MauEmail { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
