//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL_DotNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuBaoHanh
    {
        public string MaPhieuBH { get; set; }
        public string MaChiTiet { get; set; }
        public Nullable<System.DateTime> NgayTiepNhan { get; set; }
        public string NoiDungBaoHanh { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ChiTietHoaDon ChiTietHoaDon { get; set; }
    }
}
