//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class PhieuNhap
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PhieuNhap()
    {
        this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
    }

    public int PhieuNhapId { get; set; }
    public int NhanVienId { get; set; }
    public int NhaCungCapId { get; set; }
    public System.DateTime NgayNhap { get; set; }
    public decimal TongTienNhap { get; set; }
    public string TrangThai { get; set; }
    public string GhiChu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
    public virtual NhaCungCap NhaCungCap { get; set; }
    public virtual NhanVien NhanVien { get; set; }
}
