//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class PhieuThuMua
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PhieuThuMua()
    {
        this.ChiTietPhieuThuMuas = new HashSet<ChiTietPhieuThuMua>();
    }

    public int PhieuThuMuaId { get; set; }
    public int NhanVienId { get; set; }
    public int KhachHangId { get; set; }
    public System.DateTime NgayThuMua { get; set; }
    public decimal TongTienThuMua { get; set; }
    public string TrangThai { get; set; }
    public string GhiChu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ChiTietPhieuThuMua> ChiTietPhieuThuMuas { get; set; }
    public virtual KhachHang KhachHang { get; set; }
    public virtual NhanVien NhanVien { get; set; }
}
